import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Providers } from './providers';
import { cookies } from 'next/headers';
import { getServerSession } from '@lemur-bookstores/secure-stack-client/server';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const session = await getServerSession({
    cookies: cookieStore,
    tokenCookieNames: ['secure-stack.session', 'secure-stack.access-token'],
    disableRequest: true, // avoid fetch circular calls
  });

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers initialSession={session}>{children}</Providers>
      </body>
    </html>
  );
}
